/* Generated by Visual Editor */
window.COLLEGE_CONFIG = {
    "theme": "forest",
    "website": {
        "logo": "images/logo.jpg",
        "favicon": "images/logo.jpg",
        "loader": {
            "title": "TIMES PU COLLEGE",
            "subtitle": "Shaping Futures • Inspiring Excellence"
        },
        "footerText": "Times PU College, Channarayapatna, Hassan, Karnataka"
    },
    "seo": {
        "title": "Times PU College, Channarayapatna | Hassan, Karnataka",
        "description": "Times PU College is a Pre-University college located on B M Road, Channarayapatna, Hassan district, Karnataka.",
        "keywords": "Times PU College, Times PU College Channarayapatna, PU College Channarayapatna, Hassan PU College, Karnataka PU College",
        "author": "Times PU College",
        "canonicalUrl": "",
        "ogImage": "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=630&fit=crop&auto=format&q=80"
    },
    "navbar": {
        "brandName": "Times PU College"
    },
    "college": {
        "name": "TIMES PU COLLEGE",
        "shortName": "Times PU College",
        "tagline": "Learn. Lead. Succeed.",
        "establishedYear": 2014,
        "collegeCode": "LL0194",
        "address": "B M Road, Channarayapatna, Hassan, Karnataka - 573116",
        "city": "Channarayapatna",
        "district": "Hassan",
        "state": "Karnataka",
        "country": "India",
        "pincode": "573116",
        "type": "Pre-University College",
        "management": "Private Unaided",
        "gender": "Co-Educational"
    },
    "hero": {
        "title": "TIMES PU COLLEGE",
        "subtitle": "Empowering Young Minds for a Brighter Future",
        "description": "A learning environment focused on academic excellence, confidence, discipline and future readiness.",
        "image": "images/campus.jpeg",
        "locationText": "Channarayapatna, Hassan",
        "primaryButton": {
            "text": "Explore College",
            "target": "#about"
        },
        "secondaryButton": {
            "text": "Admissions",
            "target": "#admissions"
        }
    },
    "statistics": [
        {
            "key": "students",
            "value": 407,
            "label": "Students",
            "suffix": "+"
        },
        {
            "key": "faculty",
            "value": 11,
            "label": "Faculty",
            "suffix": "+"
        },
        {
            "key": "years",
            "value": "",
            "label": "Years of Excellence",
            "suffix": "+"
        },
        {
            "key": "result",
            "value": "",
            "label": "Results",
            "suffix": "%"
        },
        {
            "key": "classrooms",
            "value": 7,
            "label": "Classrooms",
            "suffix": ""
        },
        {
            "key": "new",
            "value": 0,
            "label": "New Stat",
            "suffix": ""
        }
    ],
    "about": {
        "title": "About Times PU College",
        "description": "Times PU College is a higher-secondary educational institution located in Channarayapatna, Hassan district, Karnataka. The college offers Pre-University (11th and 12th standard) education in a co-educational format.",
        "image": "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&h=800&fit=crop&auto=format&q=80",
        "highlights": [
            "Higher Secondary / Pre-University Education",
            "Co-Educational Institution",
            "Academic-focused learning environment",
            "Student development and future readiness"
        ]
    },
    "visionMission": {
        "vision": "To nurture confident, responsible and future-ready students through purposeful education.",
        "mission": "To provide a supportive academic environment that encourages learning, discipline, curiosity, skills and holistic development.",
        "values": [
            "Integrity",
            "Discipline",
            "Curiosity",
            "Respect",
            "Excellence"
        ]
    },
    "principal": {
        "name": "",
        "designation": "Principal",
        "photo": "images/principal.jpeg",
        "message": "“At TIMES, we believe marks matter, but the mindset behind them matters even more. Our goal is to help each student discover their potential, work with discipline and lead with humility.”"
    },
    "courses": [
        {
            "name": "PCMB",
            "fullName": "Physics, Chemistry, Mathematics, Biology",
            "description": "",
            "duration": "2 Years",
            "eligibility": "Verify current eligibility with the college."
        },
        {
            "name": "PCMCs",
            "fullName": "Physics, Chemistry, Mathematics, Computer Science",
            "description": "",
            "duration": "2 Years",
            "eligibility": "Verify current eligibility with the college."
        }
    ],
    "facilities": [
        {
            "name": "Library",
            "icon": "bi-book",
            "description": "Library and learning resources for students."
        },
        {
            "name": "Smart Classroom",
            "icon": "bi-display",
            "description": "Technology-enabled classroom learning environment."
        },
        {
            "name": "Laboratory",
            "icon": "bi-beaker",
            "description": "Learning facilities supporting practical education."
        },
        {
            "name": "Sports",
            "icon": "bi-trophy",
            "description": "Sports and extracurricular activities."
        },
        {
            "name": "Wi-Fi",
            "icon": "bi-wifi",
            "description": "Internet connectivity for educational use."
        },
        {
            "name": "Canteen",
            "icon": "bi-cup-hot",
            "description": "Student canteen facility."
        }
    ],
    "faculty": [],
    "achievements": [],
    "gallery": [
        {
            "category": "Campus",
            "title": "College Building",
            "description": "The main academic block.",
            "image": "images/campus.jpeg",
            "alt": "Main academic block of the college"
        },
        {
            "category": "Classrooms",
            "title": "Classroom",
            "description": "A modern classroom setup.",
            "image": "images/classroom.jpeg",
            "alt": "Empty classroom with desks"
        },
        {
            "category": "Laboratory",
            "title": "Science Laboratory",
            "description": "Practical learning environment.",
            "image": "images/Lab.jpeg",
            "alt": "Science laboratory equipment"
        },
        {
            "category": "Events",
            "title": "Student Group",
            "description": "Students during a college activity.",
            "image": "images/group.png",
            "alt": "Students working together"
        }
    ],
    "reviews": [
        {
            "name": "Rahul Gowda",
            "course": "",
            "year": "",
            "rating": 5,
            "review": "Excellent faculty and great learning environment",
            "photo": ""
        },
        {
            "name": "Ananya Reddy",
            "course": "",
            "year": "",
            "rating": 5,
            "review": "Teachers are supportive and explain concepts clearly",
            "photo": ""
        },
        {
            "name": "Karthik Shetty",
            "course": "",
            "year": "",
            "rating": 5,
            "review": "Good college with excellent academic guidance",
            "photo": ""
        }
    ],
    "admission": {
        "title": "Admissions",
        "description": "Contact Times PU College directly for current admission availability, course combinations, eligibility and required documents.",
        "eligibility": "Verify current eligibility requirements with the college.",
        "process": [
            "Contact the college",
            "Confirm course availability",
            "Confirm eligibility",
            "Submit required documents",
            "Complete admission formalities"
        ],
        "documents": [
            "SSLC / 10th Standard Marks Card",
            "Transfer Certificate",
            "Identity Proof",
            "Passport Size Photographs",
            "Other documents as requested by the college"
        ]
    },
    "contact": {
        "address": "B M Road, Channarayapatna, Hassan, Karnataka - 573116",
        "phone1": "",
        "phone2": "",
        "email": "",
        "officeHours": "",
        "mapUrl": "https://www.google.com/maps/search/?api=1&query=Times+PU+College+Channarayapatna+Karnataka"
    },
    "socialMedia": [
        {
            "platform": "whatsapp",
            "enabled": true,
            "number": "9742256509",
            "message": "Hello Times PU College, I would like to know more about admissions."
        },
        {
            "platform": "instagram",
            "enabled": true,
            "url": "https://www.instagram.com/gangatimes?igsi=MTNxcnVmY2hiN2hiYg=="
        },
        {
            "platform": "youtube",
            "enabled": false,
            "url": "https://www.youtube.com/results?search_query=Times+PU+College+Channarayapatna"
        },
        {
            "platform": "twitter",
            "enabled": false,
            "url": "https://x.com/timespucollege"
        },
        {
            "platform": "linkedin",
            "enabled": false,
            "url": "https://www.linkedin.com/school/times-pu-college-channarayapatna/"
        },
        {
            "platform": "facebook",
            "enabled": true,
            "url": "https://www.facebook.com/p/TIMES-Pre-University-College-Channarayapatna-61559244525255/"
        },
        {
            "platform": "email",
            "enabled": true,
            "email": "timespu.crpatna@gmail.com",
            "subject": "Admission Enquiry",
            "body": "Hello Times PU College, I would like to know more about admissions."
        },
        {
            "platform": "phone",
            "enabled": true,
            "number": "9742256509"
        }
    ],
    "images": {
        "logo": "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><rect width='64' height='64' rx='14' fill='%23173b6c'/><path fill='%23f4b942' d='M32 14 4 26l28 12 20-8.6V44h4V26z'/><path fill='%23f4b942' opacity='.9' d='M14 32v10c0 3 8 6 18 6s18-3 18-6V32L32 40z'/></svg>",
        "hero": "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=800&fit=crop&auto=format&q=80",
        "collegeBuilding": "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=800&fit=crop&auto=format&q=80",
        "classroom": "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&h=800&fit=crop&auto=format&q=80",
        "principal": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&h=800&fit=crop&auto=format&q=80",
        "laboratory": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1200&h=800&fit=crop&auto=format&q=80",
        "sports": "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&h=800&fit=crop&auto=format&q=80",
        "library": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1200&h=800&fit=crop&auto=format&q=80",
        "fallback": "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 300'><rect width='400' height='300' fill='%23eaf1fb'/><g fill='%23173b6c' opacity='.35'><path d='M200 110c-14 0-25 11-25 25s11 25 25 25 25-11 25-25-11-25-25-25zm-90 90h180l-45-60-35 45-25-30z'/></g><text x='50%25' y='92%25' font-family='sans-serif' font-size='14' fill='%23173b6c' opacity='.55' text-anchor='middle'>Image unavailable</text></svg>"
    }
};
window.TIMES_PU_CONFIG = window.COLLEGE_CONFIG;
